### ISSUE TITLE
Default export

### ISSUE THREAD

**Issue by kennethvandenberghe** [preactjs/preact-render-to-string#182]
Related to https://github.com/nextauthjs/next-auth/issues/1470.

We found that the default export of preact-render-to-string is not working anymore. It is giving an error that the default export is not a function.

I've been bisecting and I think that the breaking change is in https://github.com/preactjs/preact-render-to-string/commit/63fd7e1f031e5023d04f7f03d29e486de4d81f9f.

I suspected the problem was in microbundle dependency and I found out that the warning about "Using named and default exports together." starts to show up since microbundle@0.9.0.

**Comment by marvinhagemeister** [comment]
The ES-Module exports look exactly the same, but it looks like the commonjs output has changed:

`v5.1.12`:

```js
<ref *1> [Function: d] {
  render: [Circular *1],
  shallowRender: [Function (anonymous)]
}	
```	

`v5.1.13`:

```js
{
  default: <ref *1> [Function: y] {
    render: [Circular *1],
    shallowRender: [Function: v]
  },
  render: <ref *1> [Function: y] {
    render: [Circular *1],
    shallowRender: [Function: v]
  },
  renderToStaticMarkup: <ref *1> [Function: y] {
    render: [Circular *1],
    shallowRender: [Function: v]
  },
  renderToString: <ref *1> [Function: y] {
    render: [Circular *1],
    shallowRender: [Function: v]
  },
  shallowRender: [Function: v]
}
```
